### ISSUE TITLE
onClick instead of onMouseEnter

### ISSUE THREAD

**Issue by JEGardner** [plouc/react-svg-buttons#1]
Just an idea. It would be great if we could request the animation to take place on click instead of on hover - possibly passing an active state. This would particularly handy for the menu button.

**Comment by plouc** [comment]
@JEGardner, I've updated the `<NavButton />` component, and added the ability to create your own buttons using the base `<MorphIcon />` component.

Features Available in `react-svg-buttons@0.2.2`, and you have a demo of the new components [here](http://plouc.github.io/react-svg-buttons/).
